### ISSUE TITLE
Investigation: Armour for Drauven?

### ISSUE THREAD

**Issue by BoldestDungeon** [BoldestDungeon/wildermyth-drauven-pcs#139]
Is it possible to somehow allow our Drauven characters to use the existing armour slots? If so, how would we be able to do that, and how would we want it to interact with other features?

A few things to consider: 

* How will we show the proper image layers? Is there any way to easily hide the default human pieces, or will we need to mod each armour file to not show the human pieces on a `nonhuman` character?
* Do we have enough variety in armour pieces from the existing Drauven models, or will we need to create more?
* How will the armour stats interact with our existing Drauven stats? Will anything (eg: Aging) need to be tweaked to account for the possibility of additional armour to maintain game balance?
* Will the changes introduce any incompatibilities with other mods, or require us to be alert for updates to certain files in the base game?
* Is it possible to define armour that is specifically Drauven that is separate from the armour used by humans? If so, can we make it available on the crafting screen, or would it only be available as a loot drop from a battle?  If the latter, could we spawn a job on the overworld to enable crafting Drauven armour?

**Comment by Nexeron94** [comment]
Creating actual visual armor versions to fit drauven would be quite the undertaking and armor mods, that add new armors into the game will miss a drauven version. I am also unsure if human armor looks well on drauven on an aestethic level. This would probably require actual new designs for every kind of drauven. Given the fact we also want to add additional bodies for each class, we will have to create a TON of custom assets, double the amount that human characters need. I mean it would be awesome but its something we would need more manpower with clothing/armor design knowledge, which I lack in 😅 

I, however, wouldn't completely ditch armor as a feature since it's a part of character progression and choice (for example the choice of going with a piece of armor that offers more speed or more protection).

What came into my mind is following: 

- Making every piece of armor visually invisible on drauven, still allowing the stat bonuses on then. 
- Or, as my second idea, enabeling pieces of armor details on drauven depending on the equipped armor RANK.
Given that we have 3 ranks (plus the starter armor which is rank0, i believe) We can draw drauven with all details disabled on rank0 and enable more the higher the armor rank is. Maybe drauven helmets being enabled too on rank2-3. 
This way we can have visually changes without creating new assets for every piece/rank of armor and modded armor could at least have some functionality.
 
However, it all depends on whether this is possible to code or not

**Comment by BoldestDungeon** [comment]
🤔 

These are very good ideas and concerns. 

> Making every piece of armor visually invisible on drauven, still allowing the stat bonuses on then.

I don't think we can do that as an aspect on the Drauven themselves, but we could do that by modding the armour files. We should just need to add a `"ifNoOwnerAspect": "nonhuman"` to the layers defined in those files. 

The downside would be that we would need to update our copies of the armour files if/when the main game made any balance changes to armour - not the end of the world, as I don't expect those to change often, but something we would need to be aware of.

> Or, as my second idea, enabeling pieces of armor details on drauven depending on the equipped armor RANK.
Given that we have 3 ranks (plus the starter armor which is rank0, i believe) We can draw drauven with all details disabled on rank0 and enable more the higher the armor rank is. Maybe drauven helmets being enabled too on rank2-3.

Aye, this is a good idea. There's currently only ranks 0-2 for armour, but two different rank 1 and two different rank 2 armours for each class for a total of 5 per class.

We have (I think) 2 different armour variation layers for each of our Drauven in addition to the base layer, so we could use just the base layer for rank 0 and then layer on additional pieces at the higher ranks. The layer definitions could be in the armour files themselves or in our `themes/drauven.json` file - and if we're going to be modding the armour files anyways, it might make the most sense to put the layer details there. If we use what we already have as the beginning of our armour layers, then we could treat the base armour as Rank 0, use variation 1 as Rank 1/Style A, variation 2 as Rank 1/Style B, and then we would only need additional armour details that could be layered on top of (or instead of) the rank 1 variations - so that would only be 2 images per class & body type, or 12 images total.

**Comment by BoldestDungeon** [comment]
Update: Patrick shared that we can have armour apply but hide the normal visuals by using the aspect `humanSkin_suppressClothes` - so this also gets us one step closer perhaps!

He goes on to say:
> If you wanted alternate skins, I think you should be able to just use that in combination with having an aspect with skinLayers that check `ifOwnerAspect: warriorMail1` etc, and put different armor images in there. There might be issues I'm not thinking of, but, feels like it might work?

I don't know if we can get this to work _and_ have alternate skins, but it's certainly worth a try!

**Comment by BoldestDungeon** [comment]
So the one thing I think we don't get after the skin layer re-building is an ability to turn clothes off with our own `drauvenSkin_suppressClothes`

I'm going to mark this investigation as complete - I think we know what we'll need to do to make our Drauven armour-compatible, with armour artwork being the biggest task. We can whip up tasks for the 2.0 milestone based on these discoveries :)
