### ISSUE TITLE
Recruitment Event: Update "The Abandoned"

### ISSUE THREAD

**Issue by BoldestDungeon** [BoldestDungeon/wildermyth-drauven-pcs#2]
* Update event "The Abandoned" to set attributes that will allow recruiting the drauven child in subsequent chapters
* Create tiding comic 
* Create comic where the drauven finds the party and offers to join

**Comment by justEthaniguess** [comment]
Hey! Seen you're doing work on this comic in the Discord and one of the branches, and I'm liking the idea of this comic opening the potential for a new Drauven recruit! I don't know how feasible it is, but one thing from the original comic that had me concerned was the third option, where a hero can offer to kill the Drauven child. It makes sense if the party has never recruited a Drauv before and doesn't understand them as people, but I was thinking in the event that they do, a 'hero' probably shouldn't justify killing a defenceless child from a race that they know has the potential to be good.

The second option can make sense if the hero suspects it to be a trap or the party is desperate to move ahead, but I do think the third option should probably be removed in that case, or lead to a practically guaranteed and stronger 'What the hell?!' moment from the rest of the party if the hothead does choose that option, since I really doubt any rational and good person (presumably most of the party) would be alright with killing a Drauven child if they have Drauven friends. I'd probably also make the text more sensitive in general if there's any Drauven PCs around, but that might be something for the 1.0 Release.

**Comment by BoldestDungeon** [comment]
Those are excellent thoughts! I was thinking that I would tag the naysayer as such regardless and maybe generate the drauven NPC to have a rivalry with that character right out of the gates if possible. Actually going through with killing the kid should also be noted with an aspect, which would let us deal with the fallout of that choice in future events. Exactly how we want to deal with it is certainly something worth discussing for the 1.0 release :)

**Comment by BoldestDungeon** [comment]
Letting the follow-up comics be their own issues - this part is done!
