### ISSUE TITLE
Game balance: Define the Drauven aging curve

### ISSUE THREAD

**Issue by BoldestDungeon** [BoldestDungeon/wildermyth-drauven-pcs#22]
Drauven heroes can now experience the effects of age that are completely separate from what humans experience - but what do we want that to look like?

**Comment by BipenTheBat** [comment]
I think 100% we give them natural armor and warding (more armor though since a dragon's usual weakness is magic) some more block and less dodge (since in D&D dragons arent the most nimble creatures and kinda just face tank everything with their natural armor) and then as for the other stats im up in the air about since charisma for a dragon is a weird thing to think of since its both the way others view you and your personal strength
